inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'

Airbnb/DefaultScope:
  Exclude:
    - 'app/models/post.rb'

Metrics/LineLength:
  Exclude:
    - 'app/controllers/manegemants_controller.rb'
    - 'app/controllers/managemants_controller.rb'

Style/RescueModifier:
  Exclude:
    - 'app/controllers/managemants_controller.rb'
