version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: web
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    depends_on:
      - db
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0