version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"

  web:
    build: .
    environment:
      RAILS_ENV: development
    volumes:
      - .:/share_app
    ports:
      - "3000:3000"
    links:
      - db
    tty: true